# Generated by Django 5.2.1 on 2025-05-25 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cashflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflowrecord',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashflow_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashflowrecord',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashflow.category'),
        ),
        migrations.AddField(
            model_name='cashflowrecord',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashflow.status'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='cashflow.category'),
        ),
        migrations.AddField(
            model_name='cashflowrecord',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashflow.subcategory'),
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='cashflow.type'),
        ),
        migrations.AddField(
            model_name='cashflowrecord',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashflow.type'),
        ),
    ]
